version: '3'

services:
  api-dev:
    build:
      context: .
      command: npm run build
      dockerfile: Dockerfile
    ports:
      - "5006:3000"
    env_file: .env
    volumes:
      - ./src:/app/src
    command: npm start
